### ISSUE TITLE
Token contract metadata need get refreshed

### ISSUE THREAD

**Issue by anch09** [hirosystems/token-metadata-api#203]
Hi @rafaelcr , please help refresh this token contract's metadata. We are having issues with the name, symbol and image display, and also issues when trying to transfer the token from one address to another, we are getting: error 400, NoEstimateAvailable - this Stacks node has not seen this kind of contract-call before, and it cannot provide an estimate yet (https://docs.stacks.co/stacks-101/api#v2-fees-transaction). Thank you!

https://explorer.hiro.so/txid/SPZA22A4D15RKH5G8XDGQ7BPC20Q5JNMH0VQKSR6.token-ststx-earn-v1?chain=mainnet

**Comment by sabbyanandan** [comment]
Thanks for opening the issue, @anch09—we will have a look shortly.

**Comment by rafaelcr** [comment]
Done @anch09 ✅

**Comment by anch09** [comment]
> Done @anch09 ✅

Hey @rafaelcr , wondering why I'm still getting the API error for the fees estimation: error 400, NoEstimateAvailable - this Stacks node has not seen this kind of contract-call before, and it cannot provide an estimate yet (https://docs.stacks.co/stacks-101/api#v2-fees-transaction). And still not seeing the images, name and symbols on the wallets? Does it take some time to get updated?

**Comment by rafaelcr** [comment]
@anch09 that's strange, could it be cache on your browser? I see the data just fine https://api.hiro.so/metadata/ft/SPZA22A4D15RKH5G8XDGQ7BPC20Q5JNMH0VQKSR6.token-ststx-earn-v1

> error 400, NoEstimateAvailable

This seems to be a node issue and not related to this API. Can you bring this up in the core channel in the Stacks Discord server?

**Comment by anch09** [comment]
@rafaelcr an update on this, everything looks to be working fine now, just an issue with xverse when trying to transfer the token to another address. Thanks for all
